### ISSUE TITLE
Need help

### ISSUE THREAD

**Issue by volodilya** [openhomeautomation/lock-control-fingerprint#2]
Hi! 
I tried to make your device, but I have one problem. Library Adafruit_MQTT_CC3300 has been removed from GidHub. Can I ask you to send this library in my e-mail adress : volodilya@gmail.com.
Thanks!

**Comment by marcoschwartz** [comment]
Hi, I really advice moving away from the CC3000 as it's not supported anymore by Adafruit. Check my blog for more projects with the ESP8266 :)
